[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.7.6"
serde = { version = "1.0", features = ["derive"] }
clap = { version= "4.4.0", features=["derive"] }

[lib]
name = "core"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"
