[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version= "4.4.0", features=["derive"] }

[lib]
name = "core"
path = "src/lib.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"
