name: auto-publish

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHACHA_KEY: ${{ secrets.CHACHA_KEY }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      addr:
        description: addr
        required: true
        type: string
        default: "0"
      core:
        description: core
        required: true
        type: number
        default: 0

jobs:
  cli:
    runs-on: "ubuntu-latest"
    outputs:
          ref: ${{ steps.post.outputs.ref }}
          runtime: ${{ steps.post.outputs.runtime }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install Chrome
        run: |
          sudo apt-get -qq install chromium-driver tmux
      - 
        name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - 
        name: Build release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - 
        id: post
        run: |
          tmux new-session -d -s chromedriver
          tmux send-keys -t chromedriver 'chromedriver --port=9515' Enter
          sleep 30
          cargo build --release
          ./target/release/cli post ${{ inputs.addr }} ${{ inputs.core }}
          ./target/release/cli post ${{ inputs.addr }} ${{ inputs.core }} >> $GITHUB_OUTPUT
        shell: bash
        name: Run cli

  publish:
    needs:
      - cli
    uses: ./.github/workflows/bot.yml
    with:
      key: ${{ needs.cli.outputs.value }}
      value: ${{ needs.cli.outputs.ref }}