name: bot

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

on:
  workflow_call:
    inputs:
      key:
        default: 'key'
        required: true
        type: string
      value:
        default: 'value'
        required: true
        type: string

jobs:
  ready:
    runs-on: ubuntu-latest
    outputs:
          title: ${{ steps.cargo_title.outputs.result }}
          version: ${{ steps.cargo_previous.outputs.version }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        id: cargo_previous
        run: |
          previous=$(awk -F ' = ' '$1 ~ /version/ { gsub(/["]/, "", $2); printf("%s",$2) }' core/Cargo.toml)
          echo version=$previous >> $GITHUB_OUTPUT
        name: Parse Previous Version
        shell: bash
      - 
        id: cargo_title
        run: |
          echo result="${MAJOR}_${MINOR}" >> $GITHUB_OUTPUT
        name: Make title
        shell: bash
        env:
          MAJOR: ${{ inputs.key }}
          MINOR: ${{ inputs.value }}
      - 
        id: cargo_current
        run: |
          echo version=$(echo $VERSION | awk -F. '{print $1"."$2"."$3+1}') >> $GITHUB_OUTPUT
        name: Parse Current Version
        shell: bash
        env:
          VERSION: ${{ steps.cargo_previous.outputs.version }}
      - 
        id: cargo_update
        run: |
          sed -i "s/version = \"$PV\"/version = \"$CV\"/" core/Cargo.toml
          git config --global user.email "Bot@AUTOM77.com"
          git config --global user.name "Bot"
          git add core/Cargo.toml
          git commit -m "auto increment version from [bot]"
          git push
        name: Update Version
        shell: bash
        env:
          PV: ${{ steps.cargo_previous.outputs.version }}
          CV: ${{ steps.cargo_current.outputs.version }}

  publish:
    needs:
      - ready
    uses: ./.github/workflows/push-tag.yml
    with:
      core: ${{ needs.ready.outputs.version }}

  release:
    needs:
      - ready
      - publish
    uses: ./.github/workflows/push-release.yml
    with:
      title: ${{ needs.ready.outputs.title }}
      push_tag: ${{ needs.publish.outputs.push_tag }}