name: bot

on:
  workflow_call:
    inputs:
      cargo_loc:
        default: '0'
        required: true
        type: string
      cargo_bin:
        default: '0'
        required: true
        type: string
      note:
        default: 'None'
        required: true
        type: string

jobs:
  ready:
    uses: AUTOM77/Rust-Actions/.github/workflows/cargo-version.yml@main
    with:
      cargo_path: ${{ inputs.cargo_loc }}
      increment: true
    secrets: inherit

  push:
    needs:
      - ready
    uses: AUTOM77/Rust-Actions/.github/workflows/create-tag.yml@main
    with:
      version: v${{ needs.ready.outputs.version }}
    secrets: inherit

  publish:
    needs:
      - push
    uses: AUTOM77/Rust-Actions/.github/workflows/pre-release.yml@main
    with:
      push_tag: ${{ needs.push.outputs.tag }}
      note: "Hash-tag: ${{ inputs.note }}"
    secrets: inherit

  cross-release:
    needs:
      - publish
    uses: AUTOM77/Rust-Actions/.github/workflows/release-matrix.yml@main
    with:
      binary: ${{ inputs.cargo_bin }}
      pushed_tag: ${{ needs.publish.outputs.pushed_tag }}
    secrets: inherit
