name: publish

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CHACHA_KEY: ${{ secrets.CHACHA_KEY }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      addr:
        description: addr
        required: true
        type: string
        default: "0"
      core:
        description: core
        required: true
        type: number
        default: 0

jobs:
  get:
    runs-on: "ubuntu-latest"
    outputs:
          ref: ${{ steps.get.outputs.ref }}
          runtime: ${{ steps.get.outputs.runtime }}
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Chrome
        uses: nanasess/setup-chromedriver@v2.2.0
      - 
        name: Install Rust
        uses: actions-rs/toolchain@v1.0.6
        with:
          profile: minimal
          toolchain: stable
          override: true
      - 
        name: Build only
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - 
        name: Get
        id: get
        shell: bash
        run: |
          chromedriver --port=9515 &
          ./target/release/cli post ${{ inputs.addr }} ${{ inputs.core }} >> $GITHUB_OUTPUT

  publish:
    needs:
      - get
    uses: ./.github/workflows/bot.yml
    with:
      key: ${{ inputs.core }}
      value: ${{ needs.get.outputs.ref }}