name: release

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CARGO_TERM_COLOR: always

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      title:
        default: '0'
        required: true
        type: string
      push_tag:
        default: '0'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Release
        run: |
          gh release create ${{ inputs.push_tag }} --notes "Hash-tag: ${{ inputs.title }}"
        shell: bash